In [117]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1')

In [6]:
# if the respnce is 403
# then use this 
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers=headers).text

In [7]:
soup=BeautifulSoup(webpage,'lxml')

In [147]:
# print(soup.prettify())
# it will fetch the entire data of the website in html format

In [123]:
# soup.find_all('p',class='companyCardWrapper__companyLogo')

In [27]:
soup.find_all('h1')[0].text

'\n\t\t\t\t\tTop Companies in\n\t\t\t\t \n\t\t\t\t\tINDIA\n\t\t\t\t\t'

In [30]:
soup.find_all('h2')[1].text

'\n\t\t\t\t\t\t\t\t\tTCS\n\t\t\t\t\t\t\t\t'

**TO FIND OUT NAMES OF THE COMPANIES***

In [34]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [66]:
len(soup.find_all('div',class_='rating_text'))
soup.find_all('div',class_='rating_text')[0].text

'\n\t\t\t3.3'

In [41]:
len(soup.find_all('h2',class_='companyCardWrapper__companyName'))
# matlab us page me 20 companies listed hay

20

In [52]:
len(soup.find_all('span',class_='companyCardWrapper__companyRatingCount'))
# we are also getting the number of revies fron the chanels

20

In [57]:
soup.find_all('span',class_='companyCardWrapper__interLinking')[0].text
len(soup.find_all('span',class_='companyCardWrapper__interLinking'))

20

In [58]:
# so basically we are fetching the datas separately 
# to fetch in a oragnised order we will create  a entire container of the box
containers=soup.find_all('div',class_='companyCardWrapper')

In [59]:
len(containers)

20

In [149]:
name=[]
rating=[]
reviews=[]
ctype=[]
avg_salary=[]
total_jobs=[]
for i in containers :
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_='rating_text').text.strip())
    reviews.append(i.find('span','companyCardWrapper__companyRatingCount').text.strip())
    ctype.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
    avg_salary.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[1].text.strip())
    total_jobs.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[3].text.strip())

# the data we have loaded actually for only 1 page

In [150]:
name
rating
reviews
ctype
avg_salary
total_jobs

['5k',
 '22.7k',
 '4.2k',
 '955',
 '2.1k',
 '250',
 '3.2k',
 '267',
 '24',
 '699',
 '583',
 '1.7k',
 '216',
 '--',
 '15',
 '77',
 '107',
 '69',
 '563',
 '4']

In [151]:
   df=pd.DataFrame({
        'name':name,
        'rating':rating,
        'reviews':reviews,
        'company_type':ctype,
        'salary':avg_salary,
        'jobs':total_jobs
        
    })

In [152]:
df

,name,rating,reviews,company_type,salary,jobs
0,TCS,3.3,(1.2L),IT Services & Consulting | Bengaluru +448 othe...,10.3L,5k
1,Accenture,3.7,(75.2k),IT Services & Consulting | Bengaluru +261 othe...,7.1L,22.7k
2,Wipro,3.6,(66.4k),IT Services & Consulting | Hyderabad +375 othe...,4.9L,4.2k
3,Cognizant,3.7,(62.7k),IT Services & Consulting | Hyderabad +233 othe...,6.1L,955
4,Capgemini,3.6,(54.8k),IT Services & Consulting | Bengaluru +188 othe...,4.9L,2.1k
5,HDFC Bank,3.8,(53.9k),Banking | Mumbai +1866 other locations,1.5L,250
6,Infosys,3.5,(49.9k),IT Services & Consulting | Bengaluru +247 othe...,5.3L,3.2k
7,HCLTech,3.4,(47k),IT Services & Consulting | Chennai +232 other ...,3.9L,267
8,ICICI Bank,4.0,(46.7k),Banking | Mumbai +1450 other locations,1.6L,24
9,Tech Mahindra,3.3,(44.2k),IT Services & Consulting | Hyderabad +323 othe...,2.9L,699
10,Genpact,3.6,(43.4k),Analytics & KPO | Hyderabad +181 other locations,2.4L,583
11,TP,3.9,(39.7k),BPO | Mumbai +259 other locations,1L,1.7k
12,Axis Bank,3.6,(34.1k),Banking | Mumbai +1535 other locations,1L,216
13,Jio,4.4,(34.1k),Telecom | Mumbai +1966 other locations,61.9k,--
14,Concentrix Corporation,3.5,(32.9k),BPO | Bengaluru +185 other locations,1.3L,15
15,Amazon,3.9,(32.4k),Internet | Bengaluru +521 other locations,1.6L,77
16,Reliance Retail,3.9,(27.8k),Retail | Mumbai +1167 other locations,74.8k,107
17,iEnergizer,4.6,(27.5k),BPO | Noida +55 other locations,25k,69
18,LTM Limited,3.6,(27k),IT Services & Consulting | Bengaluru +146 othe...,2L,563
19,HDB Financial Services,3.9,(26.3k),NBFC | Mumbai +1099 other locations,49.3k,4

In [ ]:
# to load the entire data from the website 
final=pd.DataFrame()
for j in range(1,501):
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={j}',headers=headers).text
    soup=BeautifulSoup(webpage,'lxml')
    company=soup.find_all('div',class_='companyCardWrapper')

    name=[]
    rating=[]
    reviews=[]
    ctype=[]
    avg_salary=[]
    total_jobs=[]


    for i in company:
        try:
           name.append(i.find('h2').text.strip())
        except:
            name.append(np.nan)

        
        try:
            rating.append(i.find('div',class_='rating_text').text.strip())
        except:
            rating.append(np.nan)

        
        try:
               reviews.append(i.find('span','companyCardWrapper__companyRatingCount').text.strip())
        except:
            reviews.append(np.nan)


        try:
            ctype.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
        except:
            ctype.append(np.nan)

        
        try:
            avg_salary.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[1].text.strip())
        except:
            avg_salary.append(np.nan)


        try:
             total_jobs.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[3].text.strip())
        except:
            total_jobs.append(np.nan)

        df=pd.DataFrame({
        'name':name,
        'rating':rating,
        'reviews':reviews,
        'company_type':ctype,
        'salary':avg_salary,
        'jobs':total_jobs
        
        })
    final = pd.concat([final, df], ignore_index=True)

In [156]:
final

,name,rating,reviews,company_type,salary,jobs
0,TCS,3.3,(1.2L),IT Services & Consulting | Bengaluru +448 othe...,10.3L,5k
1,Accenture,3.7,(75.2k),IT Services & Consulting | Bengaluru +261 othe...,7.1L,22.7k
2,Wipro,3.6,(66.4k),IT Services & Consulting | Hyderabad +375 othe...,4.9L,4.2k
3,Cognizant,3.7,(62.7k),IT Services & Consulting | Hyderabad +233 othe...,6.1L,955
4,Capgemini,3.6,(54.8k),IT Services & Consulting | Bengaluru +188 othe...,4.9L,2.1k
...,...,...,...,...,...,...
9575,Amazon,3.9,(32.4k),Internet | Bengaluru +521 other locations,1.6L,77
9576,Reliance Retail,3.9,(27.8k),Retail | Mumbai +1167 other locations,74.8k,107
9577,iEnergizer,4.6,(27.5k),BPO | Noida +55 other locations,25k,69
9578,LTM Limited,3.6,(27k),IT Services & Consulting | Bengaluru +146 othe...,2L,563
9579,HDB Financial Services,3.9,(26.3k),NBFC | Mumbai +1099 other locations,49.3k,4

In [ ]:
final.shape